### ISSUE TITLE
Request:  async ecosystem monitoring

### ISSUE THREAD

**Issue by rubdos** [upsuper/areweasyncyet.rs#3]
[Some](https://www.reddit.com/r/rust/comments/ac4sje/are_we_async_yet/ed5c7b6/) [comments](https://www.reddit.com/r/rust/comments/ac4sje/are_we_async_yet/ed59nxl/) on your [reddit post](https://www.reddit.com/r/rust/comments/ac4sje/are_we_async_yet/) point towards the wish to monitor the ecosystem: tokio/romio, maybe other executors.

Since there was no issue on here to discuss how these could be represented on the areweasyncyet.rs website, I figured I should open one.

**Comment by upsuper** [comment]
Thanks for opening the issue. It's not clear to me how to show that in a useful way. Any suggestion would be appreciated.
